workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Get packages
        script: flutter pub get
      - name: Build and Package IPA
        script: |
          flutter build ios --release --no-codesign
          cd build/ios/iphoneos
          mkdir -p Payload
          mv Runner.app Payload/
          zip -r spotify.ipa Payload
          mkdir -p ../ipa
          mv spotify.ipa ../ipa/
    artifacts:
      - build/ios/ipa/*.ipa