workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Get packages
        script: flutter pub get
      - name: Build custom archive and ipa
        script: |
          flutter build ios --release --no-codesign
          cd build/ios/archive
          xcodebuild -archivePath Runner.xcarchive -exportArchive -exportOptionsPlist ../../../ios/ExportOptions.plist -exportPath ../ipa