workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Get packages
        script: flutter pub get
      - name: Build ipa and archive
        script: |
          flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa